modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "gravitycurve"
version = "1.0.0"
displayName = "Gravity Curve"
authors = "Bapmain"
description = '''
Makes the Create Cosmonautics gravity curve (start_y / full_y) configurable via JSON (Datapack).
'''

[[dependencies.gravitycurve]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gravitycurve]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gravitycurve]]
modId = "rocketnautics"
type = "required"
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "gravitycurve.mixins.json"